heat_test:
  fields:
    start:
      default: true
      selector:
        boolean:
    ignore_automations:
      default: false
      selector:
        boolean:
start_control:
relearn:
  fields:
    rooms:
      required: true
      example: '["Master Bedroom"]'
      selector:
        text:
          multiple: true
